### ISSUE TITLE
zap2epg not grabbing season-episode numbers for "The Late Show With Stephen Colbert"

### ISSUE THREAD

**Issue by RKCRLR** [edit4ever/script.module.zap2epg#12]
It grabs season & episode numbers for other shows.  I checked the zap2it.com website and the season & episode information is there.  

I'm running zap2epg 1.0 on Kodi 18.1.  Let me know if you need more information.

**Comment by cabbresson** [comment]
I've seen this happen too on other shows.

**Comment by edit4ever** [comment]
Just took a look and it does seem there have been some small changes that may be impacting things.  I'll see what I can do in the next couple of days to fix.  Thanks!

**Comment by edit4ever** [comment]
OK - I discovered that zap2it sometimes has missing data on the guides, especially ones that are a week out or more.  So the old guide data for the Colbert episodes didn't have season/episode information.  Now the data is there - but since zap2epg caches the old data to minimize downloads, the new information isn't refreshed. 

The solution is to add an option to always refresh the guide data - i.e. don't cache the downloads so the information parsed is always up to date.  I can look at adding this option.

In the meantime, just delete the XXXXXXXXXX.json.gz files from the userdata/addon_data/script.module.zap2epg/cache folder and rerun the grabber.  This will refresh all data.  You don't need to delete the SHXXXXXXXX.json or MVXXXXXXX.json files - as these are the extra details downloads, not the base guide data.

**Comment by edit4ever** [comment]
BTW - If you want to see this in action, take a look at Colbert for Wednesday March 5th...they still haven't provided information for that episode.  I'm guessing with the interview type shows - the program schedulers don't send it out until they are completely sure the lineup is set.  So for those shows - you only get a day or two out with updated info.

Maybe I can make the option adjustable, so you can set the number of days out to re-download data.  So if you want to refresh data 3 days out - it will delete the cached files and download new data for the next 3 days.  That way, if you have your downloads set to 14 days, you don't have to always download everything, just the number of days out you would like to.  Thoughts?

**Comment by wbeard52** [comment]
Yes.  That would be the best solution.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RKCRLR** [comment]
That would seem to work.  I think even one day would work for me depending on how Autorecs work in Tvheadend.  My main objective is to be able to see the episode information for recordings that have been recorded by timers.  TheTVDB needs the season & episode numbers appended to the filename so it can scrape the data.  
Thanks

**Comment by RKCRLR** [comment]
I just realized I closed this thread by accident (must have hit the close button when I posted) so I reopened it.  
Sorry for being such a newbie.

**Comment by edit4ever** [comment]
I've pushed a new release to add the ability to set the number of days to refresh the cache download.  The default setting of 1 day should be sufficient to refresh the guide data before any recordings.

Also note that if you are upgrading the addon, you may need to go into the zap2epg settings to initiate the new option.

Here's the link:
https://github.com/edit4ever/script.module.zap2epg/releases/tag/v1.2.0
