### ISSUE TITLE
Kodi 18 Leia not compatible

### ISSUE THREAD

**Issue by neo-neo1** [edit4ever/script.module.zap2epg#47]
Priceless Addon for Kodi but it's not compatible with Kodi 18 Leia (requires Python 2). 
I'm forced to use Kodi 18.9 due to other Kodi Addons not supporting Kodi 19, just like many others. Kodi 18 is still widely in use.

Please make it retrospectively compatible. 

Thank you.

**Comment by edit4ever** [comment]
Python 2 support is found in the old 1.31 version:
https://github.com/edit4ever/script.module.zap2epg/releases/download/v1.3.1/script.module.zap2epg-1.3.1.zip

This doesn't have all the other fixes - but should run fine.  There are some forks of this project that have updated this version with new fixes/features so you might want to check those out as I don't really work on this anymore.

**Comment by neo-neo1** [comment]
> There are some forks of this project that have updated this version with new fixes/features so you might want to check those out as I don't really work on this anymore.

Can you please provide naves? Thank you

**Comment by edit4ever** [comment]
I believe th0ma7's version is Python 2 compatible.

https://github.com/th0ma7/script.module.zap2epg

**Comment by neo-neo1** [comment]
> I believe th0ma7's version is Python 2 compatible.
> 
> https://github.com/th0ma7/script.module.zap2epg

It’s Python3 unfortunately. Question, where does this Addon actually store the xmltv file? I want to share it with other services. Using Kodi on Linux.

**Comment by edit4ever** [comment]
the xmltv.xml file is output in the kodi userdata zap2epg folder:  ~/.kodi/userdata/addon_data/script.module.zap2epg

If I get time, I'll take a look at updates -- but I'm not actively working on this project any longer...which is why it's being forked.  There's updates that need to happen on the Py3 version as well as the code wsas never fully cleaned up - just got to a point where it worked.  Basic functions should work fine - even on the old version.
