### ISSUE TITLE
Multiplex channels

### ISSUE THREAD

**Issue by Schmell** [edit4ever/script.module.zap2epg#5]
There does not appear to be any selections in the channelslist for multiplexed stations, like PBS for instance has 17.1 - PBS, 17.2 - create, 17.3 - PBS Kids.
I am also not able to see other channels I recieve in the channel list.

**Comment by edit4ever** [comment]
I assume you are running the latest version?  Can you let me know what zipcode so I can test on my end?

**Comment by Schmell** [comment]
m8w 2m5

**Comment by edit4ever** [comment]
What lineup?  Over the air?

**Comment by Schmell** [comment]
ya eastern time zone

**Comment by edit4ever** [comment]
OK - looks like they didn't update the Canada lineups to the newer url with the "device" code in it.  Therefore - you're not seeing the Over The Air lineup in the selection...you're just seeing the generic timezone lineups.  Which is why the subchannels are missing.

I know what how to fix it - but we'll have to keep an eye on it to see if they update the url to the newer version soon.  I should be able to update in the next hour or two.

**Comment by Schmell** [comment]
thanks

**Comment by edit4ever** [comment]
Turns out the issue is with lower case vs upper case letters on the postal code.

I will fix this (force uppercase) on my next release...but in the meantime - just change your postal code to M8W 2M5 and you should get the new lineup list with Local Over the Air Broadcast.

**Comment by edit4ever** [comment]
Closing as I assume no news is good news!
