### ISSUE TITLE
Enhancement: Delete preview pictures after x days

### ISSUE THREAD

**Issue by wbeard52** [edit4ever/script.module.zap2epg#6]
Thanks for the script.  It is working well on a Raspberry Pi 3 running OSMC.  I recently wanted to free up disk space and deleted quite a few pictures downloaded by this script.  It would be great if your script would automatically delete these program pictures after a user selectable number of days.

On my system, that path is /home/osmc/.kodi/userdata/Thumbnails

I ran this command: **`find /home/osmc/.kodi/userdata/Thumbnails/* -mtime +7 -exec rm -r {} \;`**

**Comment by edit4ever** [comment]
Since that the textures are managed by Kodi for all applications, I wouldn't want to add something in my script that deletes all thumbnails as it wouldn't just delete the epg thumbnails.  That folder should not take up that much space - but if you're still interested in occasionally deleting - you can look at something like this:  https://forum.kodi.tv/showthread.php?tid=264018

Also - by keeping the thumbnails, you speed up the epg loading as many shows are repeats.  If you want to minize the number of epg thumbnails - set the program icon option to series instead of episode.
